// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhW56qOAuCyzycLpjlf22vk3N9dh2vbPc',
    appId: '1:8361428393:web:8893a4ef235747f712f0b8',
    messagingSenderId: '8361428393',
    projectId: 'projet-5-a9405',
    authDomain: 'projet-5-a9405.firebaseapp.com',
    storageBucket: 'projet-5-a9405.appspot.com',
    measurementId: 'G-K84WMVQLWR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfnkI-7S0yjwJOMhih8Fco2t8Azc6TDCc',
    appId: '1:8361428393:android:366fd3de32bb911a12f0b8',
    messagingSenderId: '8361428393',
    projectId: 'projet-5-a9405',
    storageBucket: 'projet-5-a9405.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoKhrBJ2Eh8r6ekl2rD9iTAZDcWpTLGKw',
    appId: '1:8361428393:ios:e142926d30b0d61a12f0b8',
    messagingSenderId: '8361428393',
    projectId: 'projet-5-a9405',
    storageBucket: 'projet-5-a9405.appspot.com',
    iosBundleId: 'com.example.projet5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoKhrBJ2Eh8r6ekl2rD9iTAZDcWpTLGKw',
    appId: '1:8361428393:ios:e142926d30b0d61a12f0b8',
    messagingSenderId: '8361428393',
    projectId: 'projet-5-a9405',
    storageBucket: 'projet-5-a9405.appspot.com',
    iosBundleId: 'com.example.projet5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhW56qOAuCyzycLpjlf22vk3N9dh2vbPc',
    appId: '1:8361428393:web:db273f4470be346512f0b8',
    messagingSenderId: '8361428393',
    projectId: 'projet-5-a9405',
    authDomain: 'projet-5-a9405.firebaseapp.com',
    storageBucket: 'projet-5-a9405.appspot.com',
    measurementId: 'G-LKDXTPRLCF',
  );
}
